apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:  #these are deployment labels
    app: payment
    tier: app
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      tier: app
      project: roboshop
  template:
    metadata:
      labels: 
        app: payment
        tier: app
        project: roboshop
    spec:
      containers:
      - name: payment
        image: nishaldevops/payment:1.0.0
        envFrom: 
        - configMapRef: 
            name: payment

---
apiVersion: v1
kind: Service
metadata: 
  name: payment
  namespace: roboshop
spec: 
  selector: 
    app: payment
    tier: app
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080  #this is service port 
    targetPort: 8080 #this port belongs to container
---
apiVersion: v1 
kind: ConfigMap
metadata: 
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"


