apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:  #these are deployment labels
    app: cart
    tier: app
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      tier: app
      project: roboshop
  template:
    metadata:
      labels: 
        app: cart
        tier: app
        project: roboshop
    spec:
      containers:
      - name: cart
        image: nishaldevops/cart:1.0.0
        envFrom: 
        - configMapRef: 
            name: cart

---
apiVersion: v1
kind: Service
metadata: 
  name: cart
  namespace: roboshop
spec: 
  selector: 
    app: cart
    tier: app
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080  #this is service port 
    targetPort: 8080 #this port belongs to container
---
apiVersion: v1 
kind: ConfigMap
metadata: 
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_PORT: "8080" 
  CATALOGUE_HOST: "catalogue"

