apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:  #these are deployment labels
    app: rabbitmq
    tier: db
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      project: roboshop
      tier: db
  template:
    metadata:
      labels: #this are pod labels
        app: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq

---

  apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq
    namespace: roboshop
  spec:
    selector:
      app: rabbitmq
      tier: db
      project: roboshop
    ports:
    - name: rabbitmq-port
      protocol: TCP
      port: 5672 # this port belongs to service
      targetPort: 5672 # this port belongs to container